"""initial schema: model_versions, storms, observations, predictions

Hand-authored rather than autogenerated: this database's `postgis/postgis`
image ships pre-existing TIGER-geocoder and topology tables (spatial_ref_sys,
topology, tract, county, ...) which `alembic revision --autogenerate` picked
up as spurious "drop table" diffs. Auto-including those would have made this
migration destructive against PostGIS's own extension-owned schema, so it
was discarded in favour of this explicit version, which touches only the
four GeoStrom AI tables.

Revision ID: 0001
Revises:
Create Date: 2026-09-04
"""

from __future__ import annotations

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True)),
        sa.Column("dataset_build", sa.String(), nullable=False),
        sa.Column("split_version", sa.String()),
        sa.Column("feature_version", sa.String()),
        sa.Column("git_commit", sa.String()),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("error_radii_km", sa.JSON()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("name", "version", name="uq_model_name_version"),
    )
    op.create_index("ix_model_versions_task", "model_versions", ["task"])

    op.create_table(
        "storms",
        sa.Column("sid", sa.String(), primary_key=True),
        sa.Column("name", sa.String()),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("basin", sa.String(), nullable=False),
        sa.Column("subbasin", sa.String()),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("max_wind_kt", sa.Float()),
        sa.Column("min_pressure_hpa", sa.Float()),
        sa.Column("max_category", sa.SmallInteger()),
        sa.Column("made_landfall", sa.Boolean()),
        sa.Column("split", sa.String()),
        sa.Column("track_geom",
                 geoalchemy2.Geography(geometry_type="LINESTRING", srid=4326,
                                       spatial_index=False)),
        sa.Column("bbox",
                 geoalchemy2.Geography(geometry_type="POLYGON", srid=4326,
                                       spatial_index=False)),
    )
    op.create_index("ix_storms_season", "storms", ["season"])
    op.create_index("ix_storms_basin_season", "storms", ["basin", "season"])
    op.create_index("ix_storms_split", "storms", ["split"])
    op.execute("CREATE INDEX ix_storms_track_geom ON storms USING GIST (track_geom)")

    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("sid", sa.String(),
                 sa.ForeignKey("storms.sid", ondelete="CASCADE"), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("step_index", sa.Integer(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lon", sa.Float(), nullable=False),
        sa.Column("geom",
                 geoalchemy2.Geography(geometry_type="POINT", srid=4326,
                                       spatial_index=False), nullable=False),
        sa.Column("wind_kt", sa.Float()),
        sa.Column("pressure_hpa", sa.Float()),
        sa.Column("category", sa.SmallInteger()),
        sa.Column("nature", sa.String()),
        sa.Column("storm_speed_kt", sa.Float()),
        sa.Column("storm_dir_deg", sa.Float()),
        sa.Column("dist2land_km", sa.Float()),
        sa.Column("is_synoptic", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_observed", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("sid", "ts", name="uq_observation_sid_ts"),
        sa.CheckConstraint("lat >= -90 AND lat <= 90", name="ck_observation_lat_range"),
        sa.CheckConstraint("lon >= -180 AND lon <= 180", name="ck_observation_lon_range"),
    )
    op.create_index("ix_observations_sid_ts", "observations", ["sid", "ts"])
    op.execute("CREATE INDEX ix_observations_geom ON observations USING GIST (geom)")

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("sid", sa.String(),
                 sa.ForeignKey("storms.sid", ondelete="CASCADE"), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("origin_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lead_hours", sa.SmallInteger(), nullable=False),
        sa.Column("valid_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("model_id", sa.Integer(),
                 sa.ForeignKey("model_versions.id"), nullable=False),
        sa.Column("pred_lat", sa.Float()),
        sa.Column("pred_lon", sa.Float()),
        sa.Column("pred_geom",
                 geoalchemy2.Geography(geometry_type="POINT", srid=4326,
                                       spatial_index=False)),
        sa.Column("pred_wind_kt", sa.Float()),
        sa.Column("pred_pressure_hpa", sa.Float()),
        sa.Column("error_radius_km", sa.Float()),
        sa.Column("true_lat", sa.Float()),
        sa.Column("true_lon", sa.Float()),
        sa.Column("true_wind_kt", sa.Float()),
        sa.Column("track_error_km", sa.Float()),
        sa.Column("wind_error_kt", sa.Float()),
        sa.UniqueConstraint("sid", "origin_ts", "lead_hours", "model_id",
                            name="uq_prediction_sid_origin_lead_model"),
        sa.CheckConstraint(
            "pred_lat IS NULL OR (pred_lat >= -90 AND pred_lat <= 90)",
            name="ck_prediction_pred_lat_range"),
        sa.CheckConstraint(
            "pred_lon IS NULL OR (pred_lon >= -180 AND pred_lon <= 180)",
            name="ck_prediction_pred_lon_range"),
        sa.CheckConstraint(
            "true_lat IS NULL OR (true_lat >= -90 AND true_lat <= 90)",
            name="ck_prediction_true_lat_range"),
        sa.CheckConstraint(
            "true_lon IS NULL OR (true_lon >= -180 AND true_lon <= 180)",
            name="ck_prediction_true_lon_range"),
        sa.CheckConstraint("lead_hours > 0", name="ck_prediction_lead_hours_positive"),
    )
    op.create_index("ix_predictions_sid_origin", "predictions", ["sid", "origin_ts"])
    op.create_index("ix_predictions_model_lead", "predictions", ["model_id", "lead_hours"])
    op.create_index("ix_predictions_task", "predictions", ["task"])
    op.execute("CREATE INDEX ix_predictions_pred_geom ON predictions USING GIST (pred_geom)")


def downgrade() -> None:
    op.drop_table("predictions")
    op.drop_table("observations")
    op.drop_index("ix_storms_track_geom", table_name="storms")
    op.drop_table("storms")
    op.drop_table("model_versions")
