/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cyclones */
        get: operations["list_cyclones_api_v1_cyclones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cyclone */
        get: operations["get_cyclone_api_v1_cyclones__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones/{sid}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cyclone Observations */
        get: operations["get_cyclone_observations_api_v1_cyclones__sid__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_v1_tracks__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["get_prediction_api_v1_prediction__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/{sid}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prediction Series
         * @description Every forecast issued across the storm's life -- powers the
         *     error-growth chart (docs/API_ARCHITECTURE.md §3.5).
         */
        get: operations["get_prediction_series_api_v1_prediction__sid__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/models/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_prediction_models_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/explain/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Forecast */
        post: operations["explain_forecast_api_v1_explain_forecast_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/model-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Performance */
        get: operations["model_performance_api_v1_analytics_model_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClassificationEvidence
         * @description Structurally supported per docs/API_ARCHITECTURE.md §7's evidence
         *     packet design and the task's evidence-field list. NOT wired to a
         *     per-storm production data source in Phase 9: `db/models.py` documents
         *     that no `classifications` table exists yet (Phase 5/6 introduced a
         *     classification model, but never a production per-storm classification
         *     record) -- adding one would be a database migration, which is out of
         *     Phase 9's explicitly minimal scope. The evidence builder therefore
         *     always leaves this `None` today; the field, the validator's grounding
         *     checks for it, and the fallback template's handling of it are all fully
         *     implemented and tested against a directly-constructed `EvidencePacket`,
         *     so wiring a real source later is a data-plumbing change, not a
         *     Gemini-integration change. Documented in
         *     docs/PHASE_9_GEMINI_INTEGRATION.md as a known limitation.
         */
        ClassificationEvidence: {
            /** Class Label */
            class_label: string;
            /** Confidence */
            confidence: number | null;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
        };
        /**
         * CurrentStateEvidence
         * @description The most recent OBSERVED state at or before the forecast origin time
         *     -- never a future/predicted value (this field must never be confused
         *     with `IntensityEvidence`/`TrackEvidence`'s `forecasts`, which are model
         *     output).
         */
        CurrentStateEvidence: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Wind Kt */
            wind_kt: number | null;
            /** Pressure Hpa */
            pressure_hpa: number | null;
            /** Category */
            category: number | null;
            /** Storm Speed Kt */
            storm_speed_kt: number | null;
            /** Storm Dir Deg */
            storm_dir_deg: number | null;
            /** Dist2Land Km */
            dist2land_km: number | null;
        };
        /**
         * EvidencePacket
         * @description The ENTIRE universe of facts available to Gemini for one call, per
         *     docs/API_ARCHITECTURE.md §7. Gemini receives nothing else -- no database
         *     access, no tool, no retrieval (docs/API_ARCHITECTURE.md §6.1/§8 Layer 1).
         */
        EvidencePacket: {
            /**
             * Evidence Schema Version
             * @default v1
             * @constant
             */
            evidence_schema_version: "v1";
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            storm: components["schemas"]["StormEvidence"];
            current_state: components["schemas"]["CurrentStateEvidence"] | null;
            /** Recent History */
            recent_history: components["schemas"]["HistoryPoint"][];
            intensity: components["schemas"]["IntensityEvidence"] | null;
            track: components["schemas"]["TrackEvidence"] | null;
            classification?: components["schemas"]["ClassificationEvidence"] | null;
            /** Known Limitations */
            known_limitations: string[];
            /** Forbidden Claims */
            forbidden_claims: string[];
        };
        /**
         * ExplainRequest
         * @description `sid` is this project's established per-storm identifier, used by
         *     every other endpoint since Phase 3 (`/api/v1/prediction/{sid}`,
         *     `/api/v1/tracks/{sid}`) -- used here instead of the task prompt's
         *     illustrative `session_id`, per the task's own instruction to follow the
         *     repository's existing naming conventions.
         */
        ExplainRequest: {
            /** Sid */
            sid: string;
            /**
             * Intensity Model Version
             * @description Defaults to the recommended production intensity model (LightGBM v1)
             */
            intensity_model_version?: string | null;
            /**
             * Track Model Version
             * @description Defaults to the recommended production track model (CLIPER-style Ridge v1)
             */
            track_model_version?: string | null;
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Sid */
            sid: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Evidence Schema Version */
            evidence_schema_version: string;
            intensity_model: components["schemas"]["ModelRef"] | null;
            track_model: components["schemas"]["ModelRef"] | null;
            classification_model?: components["schemas"]["ModelRef"] | null;
            /**
             * Source
             * @description Whether the explanation came from Gemini or the deterministic fallback template -- the frontend must never have to guess this
             * @enum {string}
             */
            source: "gemini" | "fallback";
            /**
             * Fallback Reason
             * @description Set only when source='fallback': e.g. 'not_configured', 'timeout', 'malformed_json', 'ungrounded_claim'
             */
            fallback_reason?: string | null;
            /**
             * Validation Violations
             * @description Grounding-validator violation categories found in Gemini's (rejected) response, if any -- empty when source='gemini' or when Gemini was never called
             */
            validation_violations?: string[];
            explanation: components["schemas"]["GeminiStructuredResponse"];
            /** @description The exact evidence packet used to generate this explanation -- Phase 10's EvidenceDrawer renders this directly, so a viewer can inspect precisely what grounds the explanation. Contains no credentials or internal prompt text. */
            evidence: components["schemas"]["EvidencePacket"];
            /**
             * Disclaimer
             * @default Retrospective research-prototype model output. Not an operational forecast, weather warning, or safety advisory.
             */
            disclaimer: string;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: components["schemas"]["PointGeometry"] | components["schemas"]["LineStringGeometry"];
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["Feature"][];
        };
        /**
         * GeminiStructuredResponse
         * @description The constrained response schema Gemini must produce (task §10 /
         *     docs/API_ARCHITECTURE.md §8 Layer 3: structured output narrows the space
         *     in which invention can occur).
         */
        GeminiStructuredResponse: {
            /** Summary */
            summary: string;
            /** Intensity Explanation */
            intensity_explanation: string;
            /** Track Explanation */
            track_explanation: string;
            /** Classification Explanation */
            classification_explanation: string;
            /** Limitations */
            limitations: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Wind Kt */
            wind_kt: number | null;
        };
        /** IntensityEvidence */
        IntensityEvidence: {
            /**
             * Origin Ts
             * Format: date-time
             */
            origin_ts: string;
            /** Forecasts */
            forecasts: components["schemas"]["IntensityForecastPoint"][];
            context: components["schemas"]["ModelContext"];
        };
        /** IntensityForecastPoint */
        IntensityForecastPoint: {
            /** Lead Hours */
            lead_hours: number;
            /** Pred Wind Kt */
            pred_wind_kt: number | null;
            /**
             * True Wind Kt
             * @description OBSERVED verification value, if the forecast is old enough to verify
             */
            true_wind_kt?: number | null;
            /**
             * Wind Error Kt
             * @description pred - observed (DERIVED, stored)
             */
            wind_error_kt?: number | null;
        };
        /** LineStringGeometry */
        LineStringGeometry: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /**
             * Coordinates
             * @description [[lon, lat], ...]
             */
            coordinates: [
                number,
                number
            ][];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Project Name */
            project_name: string;
            /** Api Version */
            api_version: string;
            /** Active Models */
            active_models: string[];
            /**
             * Note
             * @default Retrospective research prototype. Predictions are historical baseline model output, not operational forecasts.
             */
            note: string;
        };
        /**
         * ModelContext
         * @description The model's MEASURED skill, verbatim from the committed benchmark
         *     report a `ModelVersion` row already carries -- never recomputed here.
         *     Per API_ARCHITECTURE.md §7: without this, an explanation describes a
         *     forecast as though certain; with it, Gemini can honestly say how good
         *     the model actually is.
         */
        ModelContext: {
            /** Model Name */
            model_name: string;
            /**
             * Display Name
             * @description Human-readable model name as this project's own docs describe it (e.g. 'CLIPER-style Ridge' for 'track_cliper'), computed by a fixed, deterministic lookup in the evidence builder -- never invented by Gemini
             */
            display_name: string;
            /** Model Version */
            model_version: string;
            /** Dataset Version */
            dataset_version: string;
            /**
             * Metrics By Horizon
             * @description Verbatim ModelVersion.metrics, keyed by horizon string
             */
            metrics_by_horizon: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Skill Vs Persistence Pct
             * @description Precomputed in the evidence builder from two ALREADY-STORED metric values (this model's error vs. the stored persistence model's error) -- never invented, never computed by Gemini
             */
            skill_vs_persistence_pct?: number | null;
        };
        /** ModelMetricEntry */
        ModelMetricEntry: {
            /**
             * Model Name
             * @description Internal model identifier, e.g. 'intensity_lightgbm'
             */
            model_name: string;
            /**
             * Display Name
             * @description Human-readable name, e.g. 'LightGBM'
             */
            display_name: string;
            /** Model Version */
            model_version: string;
            /**
             * Tier
             * @description 'floor' = trivial reference (majority-class/persistence context), 'baseline' = a Tier-1 production-eligible model, 'exploratory' = a research model NOT recommended for production
             * @enum {string}
             */
            tier: "floor" | "baseline" | "exploratory";
            /**
             * Is Recommended
             * @description True for exactly one model per task -- the current production baseline
             */
            is_recommended: boolean;
            /**
             * Metrics By Horizon
             * @description Intensity/track only: {'6': {...}, '12': {...}, '18': {...}, '24': {...}}
             */
            metrics_by_horizon?: {
                [key: string]: {
                    [key: string]: number;
                };
            } | null;
            /**
             * Metrics
             * @description Classification only: flat metrics (accuracy, macro_f1, ...)
             */
            metrics?: {
                [key: string]: number;
            } | null;
        };
        /** ModelPerformanceResponse */
        ModelPerformanceResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Dataset Version */
            dataset_version: string;
            /** Split Version */
            split_version: string;
            intensity: components["schemas"]["TaskComparison"];
            track: components["schemas"]["TaskComparison"];
            classification: components["schemas"]["TaskComparison"];
            /**
             * Disclaimer
             * @default Metrics are calculated on storm-disjoint held-out test data, per the project's frozen split. Retrospective evaluation only -- not a claim of operational forecasting skill.
             */
            disclaimer: string;
        };
        /** ModelRef */
        ModelRef: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Task
             * @description 'track' or 'intensity'
             */
            task: string;
            /** Dataset Build */
            dataset_build: string;
            /**
             * Metrics
             * @description Verbatim Phase 2 benchmark metrics, keyed by horizon
             */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Error Radii Km
             * @description Track models only: mean historical error (km) per horizon, for rendering an uncertainty envelope
             */
            error_radii_km?: {
                [key: string]: unknown;
            } | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ObservationOut */
        ObservationOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Wind Kt */
            wind_kt: number | null;
            /** Pressure Hpa */
            pressure_hpa: number | null;
            /** Category */
            category: number | null;
            /** Nature */
            nature: string | null;
            /** Storm Speed Kt */
            storm_speed_kt: number | null;
            /** Storm Dir Deg */
            storm_dir_deg: number | null;
            /** Dist2Land Km */
            dist2land_km: number | null;
            /** Is Synoptic */
            is_synoptic: boolean;
            /** Is Observed */
            is_observed: boolean;
            /**
             * Data Kind
             * @default observed
             */
            data_kind: string;
        };
        /** Page[StormSummary] */
        Page_StormSummary_: {
            /** Items */
            items: components["schemas"]["StormSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
            /**
             * Coordinates
             * @description [lon, lat]
             */
            coordinates: [
                number,
                number
            ];
        };
        /** PredictionOut */
        PredictionOut: {
            /** Task */
            task: string;
            /**
             * Origin Ts
             * Format: date-time
             * @description Forecast initialization time
             */
            origin_ts: string;
            /** Lead Hours */
            lead_hours: number;
            /**
             * Valid Ts
             * Format: date-time
             * @description origin_ts + lead_hours
             */
            valid_ts: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Pred Lat */
            pred_lat: number | null;
            /** Pred Lon */
            pred_lon: number | null;
            /** Pred Wind Kt */
            pred_wind_kt: number | null;
            /** Pred Pressure Hpa */
            pred_pressure_hpa: number | null;
            /** Error Radius Km */
            error_radius_km: number | null;
            /**
             * True Lat
             * @description OBSERVED ground truth at valid_ts
             */
            true_lat?: number | null;
            /** True Lon */
            true_lon: number | null;
            /** True Wind Kt */
            true_wind_kt: number | null;
            /**
             * Track Error Km
             * @description Great-circle distance, predicted vs. observed (DERIVED)
             */
            track_error_km?: number | null;
            /**
             * Wind Error Kt
             * @description predicted - observed wind (DERIVED)
             */
            wind_error_kt?: number | null;
            /**
             * Data Kind
             * @default model_prediction
             */
            data_kind: string;
            /**
             * Disclaimer
             * @default Historical baseline model prediction, not an operational forecast.
             */
            disclaimer: string;
        };
        /**
         * ProblemDetail
         * @description RFC 7807 problem+json, per docs/API_ARCHITECTURE.md §2.
         */
        ProblemDetail: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
        };
        /** StormDetail */
        StormDetail: {
            /** Sid */
            sid: string;
            /** Name */
            name: string | null;
            /** Season */
            season: number;
            /** Basin */
            basin: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** N Observations */
            n_observations: number;
            /**
             * Max Wind Kt
             * @description Lifetime max wind (kt). DISPLAY ONLY.
             */
            max_wind_kt?: number | null;
            /** Min Pressure Hpa */
            min_pressure_hpa: number | null;
            /** Max Category */
            max_category: number | null;
            /** Made Landfall */
            made_landfall: boolean | null;
            /**
             * Split
             * @description train | val | test (Phase 2 frozen split)
             */
            split?: string | null;
            /** Has Predictions */
            has_predictions: boolean;
            /**
             * Bbox
             * @description [min_lon, min_lat, max_lon, max_lat]
             */
            bbox?: number[] | null;
        };
        /** StormEvidence */
        StormEvidence: {
            /** Sid */
            sid: string;
            /** Name */
            name: string | null;
            /** Season */
            season: number;
            /** Basin */
            basin: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** N Observations */
            n_observations: number;
        };
        /** StormSummary */
        StormSummary: {
            /** Sid */
            sid: string;
            /** Name */
            name: string | null;
            /** Season */
            season: number;
            /** Basin */
            basin: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** N Observations */
            n_observations: number;
            /**
             * Max Wind Kt
             * @description Lifetime max wind (kt). DISPLAY ONLY.
             */
            max_wind_kt?: number | null;
            /** Min Pressure Hpa */
            min_pressure_hpa: number | null;
            /** Max Category */
            max_category: number | null;
            /** Made Landfall */
            made_landfall: boolean | null;
            /**
             * Split
             * @description train | val | test (Phase 2 frozen split)
             */
            split?: string | null;
        };
        /** TaskComparison */
        TaskComparison: {
            /**
             * Task
             * @enum {string}
             */
            task: "intensity" | "track" | "classification";
            /** Horizons H */
            horizons_h: number[] | null;
            /** Models */
            models: components["schemas"]["ModelMetricEntry"][];
            /**
             * Recommended Model
             * @description display_name of the recommended production model
             */
            recommended_model: string;
            /** Methodology Note */
            methodology_note: string;
        };
        /** TrackEvidence */
        TrackEvidence: {
            /**
             * Origin Ts
             * Format: date-time
             */
            origin_ts: string;
            /** Forecasts */
            forecasts: components["schemas"]["TrackForecastPoint"][];
            context: components["schemas"]["ModelContext"];
        };
        /** TrackForecastPoint */
        TrackForecastPoint: {
            /** Lead Hours */
            lead_hours: number;
            /** Pred Lat */
            pred_lat: number | null;
            /** Pred Lon */
            pred_lon: number | null;
            /**
             * Error Radius Km
             * @description Model's own historical error radius at this horizon (uncertainty cone)
             */
            error_radius_km?: number | null;
            /** True Lat */
            true_lat?: number | null;
            /** True Lon */
            true_lon?: number | null;
            /**
             * Track Error Km
             * @description Great-circle, pred vs observed (DERIVED, stored)
             */
            track_error_km?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_cyclones_api_v1_cyclones_get: {
        parameters: {
            query?: {
                season?: number | null;
                basin?: string | null;
                /** @description train | val | test */
                split?: string | null;
                /** @description substring match on storm id */
                q?: string | null;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StormSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cyclone_api_v1_cyclones__sid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cyclone_observations_api_v1_cyclones__sid__observations_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                synoptic_only?: boolean;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_v1_tracks__sid__get: {
        parameters: {
            query?: {
                /** @description Forecast origin timestamp (ISO 8601). Defaults to the storm's latest available origin. */
                t?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_api_v1_prediction__sid__get: {
        parameters: {
            query?: {
                /** @description Forecast origin timestamp. Defaults to the latest available. */
                t?: string | null;
                /** @description 'track' or 'intensity' */
                task?: string | null;
                /** @description Model name, e.g. 'track_cliper' */
                model?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_series_api_v1_prediction__sid__series_get: {
        parameters: {
            query?: {
                lead_hours?: number | null;
                task?: string | null;
                model?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_prediction_models_list_get: {
        parameters: {
            query?: {
                task?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_forecast_api_v1_explain_forecast_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_performance_api_v1_analytics_model_performance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPerformanceResponse"];
                };
            };
        };
    };
}
