/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cyclones */
        get: operations["list_cyclones_api_v1_cyclones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cyclone */
        get: operations["get_cyclone_api_v1_cyclones__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cyclones/{sid}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Cyclone Observations */
        get: operations["get_cyclone_observations_api_v1_cyclones__sid__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tracks/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Track */
        get: operations["get_track_api_v1_tracks__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/{sid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prediction */
        get: operations["get_prediction_api_v1_prediction__sid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/{sid}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Prediction Series
         * @description Every forecast issued across the storm's life -- powers the
         *     error-growth chart (docs/API_ARCHITECTURE.md §3.5).
         */
        get: operations["get_prediction_series_api_v1_prediction__sid__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prediction/models/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_v1_prediction_models_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry: components["schemas"]["PointGeometry"] | components["schemas"]["LineStringGeometry"];
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features: components["schemas"]["Feature"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthStatus */
        HealthStatus: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /** LineStringGeometry */
        LineStringGeometry: {
            /**
             * Type
             * @default LineString
             * @constant
             */
            type: "LineString";
            /**
             * Coordinates
             * @description [[lon, lat], ...]
             */
            coordinates: [
                number,
                number
            ][];
        };
        /** MetaResponse */
        MetaResponse: {
            /** Project Name */
            project_name: string;
            /** Api Version */
            api_version: string;
            /** Active Models */
            active_models: string[];
            /**
             * Note
             * @default Retrospective research prototype. Predictions are historical baseline model output, not operational forecasts.
             */
            note: string;
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Task
             * @description 'track' or 'intensity'
             */
            task: string;
            /** Dataset Build */
            dataset_build: string;
            /**
             * Metrics
             * @description Verbatim Phase 2 benchmark metrics, keyed by horizon
             */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Error Radii Km
             * @description Track models only: mean historical error (km) per horizon, for rendering an uncertainty envelope
             */
            error_radii_km?: {
                [key: string]: unknown;
            } | null;
            /** Is Active */
            is_active: boolean;
        };
        /** ObservationOut */
        ObservationOut: {
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Wind Kt */
            wind_kt: number | null;
            /** Pressure Hpa */
            pressure_hpa: number | null;
            /** Category */
            category: number | null;
            /** Nature */
            nature: string | null;
            /** Storm Speed Kt */
            storm_speed_kt: number | null;
            /** Storm Dir Deg */
            storm_dir_deg: number | null;
            /** Dist2Land Km */
            dist2land_km: number | null;
            /** Is Synoptic */
            is_synoptic: boolean;
            /** Is Observed */
            is_observed: boolean;
            /**
             * Data Kind
             * @default observed
             */
            data_kind: string;
        };
        /** Page[StormSummary] */
        Page_StormSummary_: {
            /** Items */
            items: components["schemas"]["StormSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
            /**
             * Coordinates
             * @description [lon, lat]
             */
            coordinates: [
                number,
                number
            ];
        };
        /** PredictionOut */
        PredictionOut: {
            /** Task */
            task: string;
            /**
             * Origin Ts
             * Format: date-time
             * @description Forecast initialization time
             */
            origin_ts: string;
            /** Lead Hours */
            lead_hours: number;
            /**
             * Valid Ts
             * Format: date-time
             * @description origin_ts + lead_hours
             */
            valid_ts: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Pred Lat */
            pred_lat: number | null;
            /** Pred Lon */
            pred_lon: number | null;
            /** Pred Wind Kt */
            pred_wind_kt: number | null;
            /** Pred Pressure Hpa */
            pred_pressure_hpa: number | null;
            /** Error Radius Km */
            error_radius_km: number | null;
            /**
             * True Lat
             * @description OBSERVED ground truth at valid_ts
             */
            true_lat?: number | null;
            /** True Lon */
            true_lon: number | null;
            /** True Wind Kt */
            true_wind_kt: number | null;
            /**
             * Track Error Km
             * @description Great-circle distance, predicted vs. observed (DERIVED)
             */
            track_error_km?: number | null;
            /**
             * Wind Error Kt
             * @description predicted - observed wind (DERIVED)
             */
            wind_error_kt?: number | null;
            /**
             * Data Kind
             * @default model_prediction
             */
            data_kind: string;
            /**
             * Disclaimer
             * @default Historical baseline model prediction, not an operational forecast.
             */
            disclaimer: string;
        };
        /**
         * ProblemDetail
         * @description RFC 7807 problem+json, per docs/API_ARCHITECTURE.md §2.
         */
        ProblemDetail: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
        };
        /** StormDetail */
        StormDetail: {
            /** Sid */
            sid: string;
            /** Name */
            name: string | null;
            /** Season */
            season: number;
            /** Basin */
            basin: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** N Observations */
            n_observations: number;
            /**
             * Max Wind Kt
             * @description Lifetime max wind (kt). DISPLAY ONLY.
             */
            max_wind_kt?: number | null;
            /** Min Pressure Hpa */
            min_pressure_hpa: number | null;
            /** Max Category */
            max_category: number | null;
            /** Made Landfall */
            made_landfall: boolean | null;
            /**
             * Split
             * @description train | val | test (Phase 2 frozen split)
             */
            split?: string | null;
            /** Has Predictions */
            has_predictions: boolean;
            /**
             * Bbox
             * @description [min_lon, min_lat, max_lon, max_lat]
             */
            bbox?: number[] | null;
        };
        /** StormSummary */
        StormSummary: {
            /** Sid */
            sid: string;
            /** Name */
            name: string | null;
            /** Season */
            season: number;
            /** Basin */
            basin: string;
            /**
             * Start Time
             * Format: date-time
             */
            start_time: string;
            /**
             * End Time
             * Format: date-time
             */
            end_time: string;
            /** N Observations */
            n_observations: number;
            /**
             * Max Wind Kt
             * @description Lifetime max wind (kt). DISPLAY ONLY.
             */
            max_wind_kt?: number | null;
            /** Min Pressure Hpa */
            min_pressure_hpa: number | null;
            /** Max Category */
            max_category: number | null;
            /** Made Landfall */
            made_landfall: boolean | null;
            /**
             * Split
             * @description train | val | test (Phase 2 frozen split)
             */
            split?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_cyclones_api_v1_cyclones_get: {
        parameters: {
            query?: {
                season?: number | null;
                basin?: string | null;
                /** @description train | val | test */
                split?: string | null;
                /** @description substring match on storm id */
                q?: string | null;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StormSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cyclone_api_v1_cyclones__sid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StormDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cyclone_observations_api_v1_cyclones__sid__observations_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                synoptic_only?: boolean;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservationOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_track_api_v1_tracks__sid__get: {
        parameters: {
            query?: {
                /** @description Forecast origin timestamp (ISO 8601). Defaults to the storm's latest available origin. */
                t?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_api_v1_prediction__sid__get: {
        parameters: {
            query?: {
                /** @description Forecast origin timestamp. Defaults to the latest available. */
                t?: string | null;
                /** @description 'track' or 'intensity' */
                task?: string | null;
                /** @description Model name, e.g. 'track_cliper' */
                model?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prediction_series_api_v1_prediction__sid__series_get: {
        parameters: {
            query?: {
                lead_hours?: number | null;
                task?: string | null;
                model?: string | null;
            };
            header?: never;
            path: {
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_v1_prediction_models_list_get: {
        parameters: {
            query?: {
                task?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
